version: '2'
services:
   mysql:
     env_file: .env
     image: mysql:5.7
     volumes:
        - ./sql:/docker-entrypoint-initdb.d:rw
     restart: always
   wordpress:
     env_file: .env
     depends_on:
       - mysql
     image: ejingfx/wp-mix:latest
     ports:
       - 8000:80
     volumes:
       - ./wordpress:/var/www/html
     restart: always